### ISSUE TITLE
Non UI Config

### ISSUE THREAD

**Issue by somehowchris** [piwik/plugin-QueuedTracking#147]
Hey :)

Love the plugin but as I upgrade one of my instances to some new infra I ran into some problems.

We I move to k8s I would need to have the plugin to be configured on startup as my Vault service would provide credentials to redis which are rotating and once they rotate the instance would be restarted.

Is it possible to configure the plugin via the ini file? (which then can be configured via the EnvironmentVariables plugin)

**Comment by tsteur** [comment]
Hi @somehowchris 

this is possible. You can go to Matomo as super user, then Administration -> Config file in the left menu. Click on the Queued tracking section to see the possible settings.

You can configure for example 

```ini
[QueuedTracking]
numRequestsToProcess = 25
numQueueWorkers = 1
backend = mysql
...
```

When you configure it in the settings, it will disappear from the UI automatically. Hope this helps @somehowchris

**Comment by somehowchris** [comment]
hey @tsteur 

I have seen that page but I'm a bit worried/confused as I can only see a bunch of the ones which are available by the UI. To fully configure for redis there should at least be another 2 options about redis.

Neither do I see any documentation about this on the [marketplace](https://plugins.matomo.org/QueuedTracking#preview).

My options on the config files page:
<img width="240" alt="Bildschirmfoto 2021-04-18 um 22 15 09" src="https://user-images.githubusercontent.com/38954618/115159519-c757f880-a093-11eb-8ba1-5e6f249276c5.png">

**Comment by tsteur** [comment]
@somehowchris I'm seeing below settings:

![image](https://user-images.githubusercontent.com/273120/115159667-6b6b8f00-a0e8-11eb-92cb-c5cedc3aee6f.png)

All these options should work. Maybe there are already some config settings for queued tracking in your config ini php or so? That `PluginsInstalled[]` appears there for example isn't expected and sounds like some kind of misconfiguration (like a syntax problem or so, never seen it before) or maybe `PluginsInstalled[]` was copied there by accident. You'll also want to make sure that the queued tracking plugin is enabled, otherwise those options won't appear in this UI.

**Comment by tsteur** [comment]
Could you try the above options and see if that works?
