### ISSUE TITLE
Enable queuedtracking settings override from config file (to omit DB-stored setting)

### ISSUE THREAD

**Issue by jaceklubzinski** [piwik/plugin-QueuedTracking#21]
In some configurations, it would be very useful set plugin parameter from the configuration file. Especially if we want to separate standard tracking requests and import logs (use different instances of redis)

**Comment by quba** [comment]
Example use case is when users want to use Redis for standard JS tracking and don't want to when using log import. Currently all requests hit the Redis queue and QueuedTracking plugin was not designed to support log import.

**Comment by tsteur** [comment]
This could be a separate plugin. I possibly wouldn't include it in QueuedTracking itself since it might be confusing to have setting in DB and Config and which one wins over the other one. Of course we could disable the setting in the UI with another config but could have some side effects. Would be okay to have this in another plugin or does it have to be in this plugin?

**Comment by quba** [comment]
As for me it doesn't matter. The only thing is that it may be more difficult to maintain a separate plugin.

**Comment by tsteur** [comment]
Just one other random idea: Is it possible to maybe just activate in one instance the plugin and in the other instance not activate the plugin? This way you also change it in the config

**Comment by quba** [comment]
This solves only one use case. E.g. on cloud in order to automate everything, we'd like to be able to configure everything in config file and use a few different instances of Redis.

**Comment by tsteur** [comment]
OK, is it needed in Cloud already or could we maybe go for now this solution? Just asking

**Comment by tsteur** [comment]
When we work on a solution for this, we could maybe try to find a global solution for all system settings to be able to overwrite any system setting. Eg `[QueuedTracking]isEnabled=false`. This would require changes in core though and there's a risk of breaking things etc so nothing for 2.15.

It would be good if we could for now go with the solution to remove the plugin from `config.ini.php` and implement for Piwik 3.0 a solution to allow overwriting any setting via config.

**Comment by tsteur** [comment]
I had a look here. What would be easy to implement is to be able to overwrite any setting (eg `[QueuedTracking]isEnabled=false`) via config. We would still show it in the UI though and the shown value in the UI might not be the same as the one in config. Hiding the "Enabled" setting in the UI when eg `[QueuedTracking]isEnabled=false` is set is quite a bit of work and would be ideally only done after refactoring the Settings API in Piwik 3.0 https://github.com/piwik/piwik/issues/7893#issuecomment-121532574 . We could already start a refactoring now but there's some danger to break things.

Otherwise back to the question in https://github.com/piwik/plugin-QueuedTracking/issues/21#issuecomment-152855327 ? Is it actually already needed in the cloud now or can we maybe go with suggested solution in https://github.com/piwik/plugin-QueuedTracking/issues/21#issuecomment-152315416 ?

**Comment by quba** [comment]
We need to be able to configure everything from the config file (enable/disable, configure redis host and db, configure other settings). If this won't be possible, we will have to create hacks (scripts that modify piwik_option table).

**Comment by tsteur** [comment]
This is solved in https://github.com/piwik/piwik/pull/9521 and will be probably merged soon. Feel free to test it
