### ISSUE TITLE
When importing logs, got Fatal error: Incorrect response from tracking API: 'GIF89a�!�,D;'

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-QueuedTracking#5]
When queuedTracking plugin is enabled, when importing server logs, I get the following:

```
$ ./misc/log-analytics/import_logs.py --url=demo2.piwik.org  ~/admin/log/access.log --idsite=4
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Parsing log /home/piwik-demo2/admin/log/access.log...
Fatal error: Incorrect response from tracking API: 'GIF89a�!�,D;'
Is the BulkTracking plugin disabled?
```

Can we fix this issue in QueuedTracking plugin directly or does it need to be fixed in core? hopefully we can fix it in QueuedTracking as we need it ASAP

**Comment by tsteur** [comment]
See Readme

> In case you are using bulk tracking the bulk tracking response varies compared to the regular one. We will always return either an image or a 204 HTTP response code in case the parameter send_image=0 is sent.

This is currently expected behaviour. The log importer was recently changed to trigger a fatal when it does not return json which causes that message: https://github.com/piwik/piwik/issues/6982 Importing itself should work fine.

**Comment by tsteur** [comment]
Should be fixed in https://github.com/piwik/piwik-log-analytics/issues/57

A temporary workaround was done in https://github.com/piwik/plugin-QueuedTracking/commit/f918c2ba022cdf0b8eea940f78c266e5b65c7c4a but we will remove this again after https://github.com/piwik/piwik-log-analytics/issues/57 was fixed and released see https://github.com/piwik/piwik/issues/7595

Be aware that we temporarily change the API output meaning this breaks temporarily the API
