### ISSUE TITLE
Queue never process

### ISSUE THREAD

**Issue by scottdre1** [piwik/plugin-QueuedTracking#7]
I am using an AWS EC2 and RDS (no Infile permission - 1 Billion PVs / month - Redis Server V 3.0.0) and whenever I try to enable the "queue tracking" I get this message : "WARNING: .../plugins/QueuedTracking/SystemCheck.php(35): Warning - version_compare() expects parameter 1 to be string, array given - Piwik 2.13.1"

I can see Redis is writting into the Dump file but it never get sent to the MySQL Database. When I try to process the queue manually I get this message " Nothing to proccess. XX request sets are queued and they are already in process by another script." even if set the process after 5 requests it still goes up to 10 000 and never process...

Can you please support me with this issue ?

Many Thanks !

**Comment by tsteur** [comment]
I just pushed a change so that the warning should no longer appear. I will release a new version shortly. 

Which Redis version are you using? Somehow it seems to fail to perform a `info server`. Is this maybe blocked? It does a check there to require at least Redis 2.8.0. Otherwise the queue won't work correctly.

**Comment by tsteur** [comment]
@scottdre1 do you have any update on this?

**Comment by tsteur** [comment]
Will close it, please reopen in case you can still reproduce
